### ISSUE TITLE
Seminário TCC II - 04/11

### ISSUE THREAD

**Issue by edeciofernando** [jthanlopes/SysGAP#15]
Considerações:
- Ok. Muito bom, sistema com vários recursos interessantes sobre o tema.

Sugestões:

- [ ] Filtro por cidade, permitir + de uma cidade
- [ ] Login, avaliar localização da troca Login Sou Empresa ou Sou FreeLancer
- [ ] Cuidado com o prazo da escrita do artigo

**Comment by jthanlopes** [comment]
Quanto ao login.
Coloquei o símbolo "+", para dar a ideia de mais opções.
![image](https://user-images.githubusercontent.com/17733564/32410508-d40972a2-c1a8-11e7-8e6c-2f748af88331.png)
E na home, na seção "Sobre o Projeto", coloquei links para as telas de login.
![image](https://user-images.githubusercontent.com/17733564/32410554-271ad084-c1aa-11e7-873c-da5abdb93023.png)

**Comment by jthanlopes** [comment]
Implementado o filtro para permitir selecionar mais de uma cidade.
![image](https://user-images.githubusercontent.com/17733564/32445033-a61aa85e-c2eb-11e7-922b-d3a6c8702412.png)
