### ISSUE TITLE
Seminário Final TCC I

### ISSUE THREAD

**Issue by edeciofernando** [jthanlopes/SysGAP#4]
Sugestões:
* Cuidados gramaticais: "facha"
* Cuidado com a escrita informal: "Eu irei apresentar", "conheci e entendi..."
* Em sistemas similares, destacar o diferencial do teu sistema.
* CRUD -> na primeira citação, colocar por extenso.
* Git... "lidar com tudo..." (evitar)
* Tecnologias: padronizar tamanho dos parágrafos.
* ER muito pequeno
* Na figura 9 serão ... (pontuar) são...

Tarefas:
- [ ] Adicionar Referência no subcapítulo sobre MariaDB
- [ ] Sistema: nível -> categorizar

**Comment by jthanlopes** [comment]
Sugestões realizadas:

Cuidados gramaticais: "facha"
Cuidado com a escrita informal: "Eu irei apresentar", "conheci e entendi..."
CRUD -> na primeira citação, colocar por extenso.
Git... "lidar com tudo..." (evitar)
Na figura 9 serão ... (pontuar) são...

**Comment by jthanlopes** [comment]
Tarefas concluídas:

 Adicionar Referência no subcapítulo sobre MariaDB.
 Sistema: nível -> categorizar.

**Comment by jthanlopes** [comment]
Sugestão concluída:

Tecnologias: padronizar tamanho dos parágrafos.

**Comment by jthanlopes** [comment]
Sugestões e tarefas concluídas.
