### ISSUE TITLE
Seminário Final  TCC-1

### ISSUE THREAD

**Issue by angelogluz** [jthanlopes/SysGAP#5]
**Sugestões**
* Tomar cuidado com fontes em caixa alta

**Tarefas**
* [ ]  Organizar todas as tarefas a serem executadas no TCC-2 em issues e milestones
* [ ] Verificar pontuações no final dos marcadores (apresentação)
* [ ] AdminLTE não aparece em lugar algum no relatório --> Inserir

**Comment by jthanlopes** [comment]
Sugestões e tarefas finalizadas.
